# Build stage
FROM node:22-alpine AS workspace

WORKDIR /monorepo

# Copy root files
COPY pnpm-workspace.yaml pnpm-lock.yaml package.json* ./
COPY packages ./packages
COPY apps/api ./apps/api

# Setup pnpm
RUN corepack enable && corepack prepare pnpm@10.24.0 --activate

# Install dependencies
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile

# Build the selected app
RUN cd apps/api && pnpm run build:api

# Deploy production dependencies only
RUN pnpm --filter api --prod --legacy deploy ./api-deploy

# Manually copy dist into deploy folder
RUN cp -r apps/api/dist ./api-deploy/dist

# Production stage
FROM node:22-alpine
WORKDIR /app

# Copy the deployed app
COPY --from=workspace /monorepo/api-deploy ./

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000
CMD ["node", "dist/apps/api/apps/user-api/src/main.js"]